name: Half-year calendar

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Half-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes

      - name: Update README
        uses: Emmeline1101/README@main
        with:
          repo_path: Emmeline1101  # 修改为仓库的名称
          file_path: README.md
          COMMIT_MSG: "Updated README with recent activity"
          MAX_LINES: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

