name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Half-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes

      - name: Read README template
        id: read-readme
        run: echo ::set-output name=README_CONTENT::$(cat README.md)

      - name: Update README
        run: echo "${{ steps.read-readme.outputs.README_CONTENT }}" > README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
